//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GENAP_MAUI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GENAP_MAUI.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Balance of.
        /// </summary>
        public static string Balance_label {
            get {
                return ResourceManager.GetString("Balance_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steel blue_Yellow_Green_Purple_Aqua_Orange_Red_Emerald_Cyan_Indigo_Magenta.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View charts ›.
        /// </summary>
        public static string GoToGraphs_caption {
            get {
                return ResourceManager.GetString("GoToGraphs_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See all ›.
        /// </summary>
        public static string GoToTransactions_caption {
            get {
                return ResourceManager.GetString("GoToTransactions_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly activity.
        /// </summary>
        public static string Month_summary_label {
            get {
                return ResourceManager.GetString("Month_summary_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown_January_February_March_Aril_My_June_July_August_September_October_November_December.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display in.
        /// </summary>
        public static string PickerDisplay_caption {
            get {
                return ResourceManager.GetString("PickerDisplay_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your money, your control..
        /// </summary>
        public static string Tagline_caption {
            get {
                return ResourceManager.GetString("Tagline_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Today_Last 30 days_This month_Last 3 months_Last 6 months_Last year_All time_Projection.
        /// </summary>
        public static string TimePeriods {
            get {
                return ResourceManager.GetString("TimePeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome,.
        /// </summary>
        public static string Welcome_title {
            get {
                return ResourceManager.GetString("Welcome_title", resourceCulture);
            }
        }
    }
}
